#############################################################################
# Makefile for building: TSEnew
# Generated by qmake (2.01a) (Qt 4.6.4) on: Wed Jul 30 16:24:13 2014
# Project:  TSEnew.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.6.4/bin/qmake -unix -o Makefile TSEnew.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.6.4/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.6.4/include/QtCore -I/usr/local/Trolltech/Qt-4.6.4/include/QtNetwork -I/usr/local/Trolltech/Qt-4.6.4/include/QtGui -I/usr/local/Trolltech/Qt-4.6.4/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/Qt-4.6.4/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.6.4/lib -lQtGui -L/usr/local/Trolltech/Qt-4.6.4/lib -L/usr/X11R6/lib -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-4.6.4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		AppViewer.cpp \
		PLog.cpp \
		FileDownload.cpp moc_AppViewer.cpp \
		moc_FileDownload.cpp \
		qrc_resources.cpp
OBJECTS       = main.o \
		AppViewer.o \
		PLog.o \
		FileDownload.o \
		moc_AppViewer.o \
		moc_FileDownload.o \
		qrc_resources.o
DIST          = /usr/local/Trolltech/Qt-4.6.4/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/include_source_dir.prf \
		TSEnew.pro
QMAKE_TARGET  = TSEnew
DESTDIR       = 
TARGET        = TSEnew

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_TSEApps.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TSEnew.pro  /usr/local/Trolltech/Qt-4.6.4/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.6.4/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.6.4/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.6.4/lib/libQtCore.prl \
		/usr/local/Trolltech/Qt-4.6.4/lib/libQtNetwork.prl
	$(QMAKE) -unix -o Makefile TSEnew.pro
/usr/local/Trolltech/Qt-4.6.4/mkspecs/common/g++.conf:
/usr/local/Trolltech/Qt-4.6.4/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.6.4/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.6.4/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.6.4/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.6.4/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.6.4/lib/libQtCore.prl:
/usr/local/Trolltech/Qt-4.6.4/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile TSEnew.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/TSEnew1.0.0 || $(MKDIR) .tmp/TSEnew1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/TSEnew1.0.0/ && $(COPY_FILE) --parents AppViewer.h PLog.h FileDownload.h .tmp/TSEnew1.0.0/ && $(COPY_FILE) --parents resources.qrc .tmp/TSEnew1.0.0/ && $(COPY_FILE) --parents main.cpp AppViewer.cpp PLog.cpp FileDownload.cpp .tmp/TSEnew1.0.0/ && $(COPY_FILE) --parents TSEApps.ui .tmp/TSEnew1.0.0/ && (cd `dirname .tmp/TSEnew1.0.0` && $(TAR) TSEnew1.0.0.tar TSEnew1.0.0 && $(COMPRESS) TSEnew1.0.0.tar) && $(MOVE) `dirname .tmp/TSEnew1.0.0`/TSEnew1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/TSEnew1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_AppViewer.cpp moc_FileDownload.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_AppViewer.cpp moc_FileDownload.cpp
moc_AppViewer.cpp: ui_TSEApps.h \
		FileDownload.h \
		PLog.h \
		AppViewer.h
	/usr/local/Trolltech/Qt-4.6.4/bin/moc $(DEFINES) $(INCPATH) AppViewer.h -o moc_AppViewer.cpp

moc_FileDownload.cpp: FileDownload.h
	/usr/local/Trolltech/Qt-4.6.4/bin/moc $(DEFINES) $(INCPATH) FileDownload.h -o moc_FileDownload.cpp

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		Resources/group.png \
		Resources/grid.png \
		Resources/loading.png \
		Resources/spread.png \
		Resources/list.png \
		Resources/thinspace.png \
		Resources/reset.png \
		Resources/uniform.png \
		Resources/home.png
	/usr/local/Trolltech/Qt-4.6.4/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_TSEApps.h
compiler_uic_clean:
	-$(DEL_FILE) ui_TSEApps.h
ui_TSEApps.h: TSEApps.ui
	/usr/local/Trolltech/Qt-4.6.4/bin/uic TSEApps.ui -o ui_TSEApps.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp AppViewer.h \
		ui_TSEApps.h \
		FileDownload.h \
		PLog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

AppViewer.o: AppViewer.cpp AppViewer.h \
		ui_TSEApps.h \
		FileDownload.h \
		PLog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AppViewer.o AppViewer.cpp

PLog.o: PLog.cpp PLog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PLog.o PLog.cpp

FileDownload.o: FileDownload.cpp FileDownload.h \
		PLog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FileDownload.o FileDownload.cpp

moc_AppViewer.o: moc_AppViewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AppViewer.o moc_AppViewer.cpp

moc_FileDownload.o: moc_FileDownload.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FileDownload.o moc_FileDownload.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/ || $(MKDIR) $(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/ 


install_sources: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/ || $(MKDIR) $(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/ 
	-$(INSTALL_PROGRAM) /home/vijender/mandar/TSE/new/main.cpp $(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/
	-strip $(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/main.cpp
	-$(INSTALL_PROGRAM) /home/vijender/mandar/TSE/new/AppViewer.cpp $(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/
	-strip $(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/AppViewer.cpp
	-$(INSTALL_FILE) /home/vijender/mandar/TSE/new/PLog.cpp $(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/
	-$(INSTALL_FILE) /home/vijender/mandar/TSE/new/FileDownload.cpp $(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/
	-$(INSTALL_PROGRAM) /home/vijender/mandar/TSE/new/AppViewer.h $(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/
	-strip $(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/AppViewer.h
	-$(INSTALL_FILE) /home/vijender/mandar/TSE/new/PLog.h $(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/
	-$(INSTALL_FILE) /home/vijender/mandar/TSE/new/FileDownload.h $(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/
	-$(INSTALL_PROGRAM) /home/vijender/mandar/TSE/new/TSEnew.pro $(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/
	-strip $(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/TSEnew.pro


uninstall_sources:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/main.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/AppViewer.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/PLog.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/FileDownload.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/AppViewer.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/PLog.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/FileDownload.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/TSEnew.pro
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/Trolltech/Qt-4.6.4/examples/layouts/borderlayout/ 


install:  install_target install_sources  FORCE

uninstall: uninstall_target uninstall_sources   FORCE

FORCE:

